### ISSUE TITLE
Build failure with Python 3.9.0

### ISSUE THREAD

**Issue by fxcoudert** [sshock/AFFLIBv3#44]
afflib 3.7.19 does not build with Python 3.9.0 (https://github.com/Homebrew/homebrew-core/pull/62560), it gives the following error:

```
pyaff.c:2831:28: error: no member named 'tp_print' in 'struct _typeobject'
```

because (https://docs.python.org/3.9/whatsnew/3.9.html):

> The tp_print slot of PyTypeObject has been removed. It was used for printing objects to files in Python 2.7 and before. Since Python 3.0, it has been ignored and unused

I suspect pyaff.c needs to be updated with a newer Cython.

**Comment by sshock** [comment]
@fxcoudert I updated it; can you see if it works now?
